# Generated by Django 3.1.6 on 2021-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
